config/routes.rb
Rails.application.routes.draw do
  resources :owners
  resources :items
  resources :order_items
  resources :orders
  resources :customers

  namespace :api do
    namespace :v1 do
      post '/login', to: 'auth#create'

    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :orderItems
    has_many :orders, through: :orderItem
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer, optional: true
    has_many :orderItems
    has_many :items, through: :orderItems
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order, optional: true
    belongs_to :item, optional: true

    
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_secure_password
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApplicationController
    def create
        @user = Owner.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            token = encode("user_id": @user.id)
            render json: {
            authenticated: true,
            token: token,
            user: @user,
            }, status: :accepted
        else
            render json: {
            authenticated: false,
            message: "login failed"
            }, status: :unauthorized 
        end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API

    def secret_key
        "secret"
    end

    # Given a payload, and a secret, return a token
    def encode(payload)
        JWT.encode(payload, secret_key, "HS256")
    end

    # Given a token, and secret key, return payload
    def decode(token)
        JWT.decode(token, secret_key, true, {algorithm: "HS256"})[0]
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    render json: Item.all
  end
  
  def show
    item = Item.find(params[:id])
    render json: item
  end

  def create
    item = Item.new(item_params)
    if item.save
      render json: item
    end
  end

  def update
    item = Item.find(params["id"])
    item.update(:name, :price, :image)
  end

  def destroy
    item = Item.destroy(params[:id])
    render json: Item.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :image, :category)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
    def index
        render json: OrderItem.all
    end

    def show 
        oi = OrderItem.find(params["id"].to_i)
        render json: oi
    end
end

app/controllers/orders_controller.rb
require 'date'

class OrdersController < ApplicationController
  def index
    token = request.headers["Authentication"].split(" ")[1]
    @owner = Owner.find(decode(token)["user_id"])
    if @owner
      result = Order.find_by_sql(
        "SELECT orders.id, orders.date, orders.address, orders.comments, orders.status, 
        customers.first_name, customers.last_name, customers.email
        from orders INNER JOIN customers
        ON customers.id = orders.customer_id")
      render json: result
    else
      render json: {
        authenticated: false,
        message: "must be an owner"
      }, status: :unauthorized 
    end
  end
  
  def show
    token = request.headers["Authentication"].split(" ")[1]
    @owner = Owner.find(decode(token)["user_id"])
    if @owner
      # order = OrderItem.where(order_id: params[:id])
      # render json: order
      result = OrderItem.find_by_sql(
        "SELECT order_items.item_id, order_items.quantity,
        items.name, items.price, items.image, items.category
        from order_items INNER JOIN items
        ON order_items.item_id = items.id where order_items.order_id = " + params[:id] )
      render json: result
    else
      render json: {
        authenticated: false,
        message: "must be an owner"
      }, status: :unauthorized 
    end
  end

  def create
    customer = Customer.find_or_create_by(
                first_name: params["first_name"],
                last_name: params["last_name"],
                email: params["email"]
    )
    order = Order.new(
      customer_id: customer["id"], 
      date: Date.parse(params["date"]),
      address: params["address"],
      comments: params["comments"],
      status: "pending"
    )

    if order.save
      items = params['items']
    
      errors = []
      for item in items
         orderitem = OrderItem.new(
          item_id: item["item_id"],
          order_id: order.id,
          quantity: item["quantity"]
        )
        if !orderitem.save
          errors.push(orderitem.errors)
        end
      end

      if errors.length > 0
        render json: {:errors => errors}, :status => 500
      else
        render json: {}
      end
    end
  end
  
  def destroy
    Order.destroy(params[:id])
    render json: Order.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_id, :date, :address, :comments, :status)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_detail_helper.rb
module OrderDetailHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :itemName %>
    <%= form.text_field :itemName %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :foodType %>
    <%= form.text_field :foodType %>
  </div>

  <div class="field">
    <%= form.label :qunanty %>
    <%= form.number_field :qunanty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Itemname</th>
      <th>Price</th>
      <th>Foodtype</th>
      <th>Qunanty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.itemName %></td>
        <td><%= item.price %></td>
        <td><%= item.foodType %></td>
        <td><%= item.qunanty %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Itemname:</strong>
  <%= @item.itemName %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Foodtype:</strong>
  <%= @item.foodType %>
</p>

<p>
  <strong>Qunanty:</strong>
  <%= @item.qunanty %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaterBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= form_with(model: order_item, local: true) do |form| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
        <% order_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.number_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :qunanty %>
    <%= form.number_field :qunanty %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Item</th>
      <th>Qunanty</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.order_id %></td>
        <td><%= order_item.item_id %></td>
        <td><%= order_item.qunanty %></td>
        <td><%= order_item.comment %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @order_item.item_id %>
</p>

<p>
  <strong>Qunanty:</strong>
  <%= @order_item.qunanty %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @order_item.comment %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Date</th>
      <th>Address</th>
      <th>Comments</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer_id %></td>
        <td><%= order.date %></td>
        <td><%= order.address %></td>
        <td><%= order.comments %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @order.comments %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>